from RPi import GPIO

# PIN DEL RASPBERRY DI MOVIMENTO MOTORI
PIN_STEP_MOTORE_ASSE_Y = 20
PIN_STEP_MOTORE_ASSE_X = 16
PIN_STEP_MOTORE_ASSE_Z1 = 12  # Z1 e' il motore di sinistra
PIN_STEP_MOTORE_ASSE_Z2 = 25  # Z2 e' il motore di destra

# PIN DEL RASPBERRY DI SENSO DI ROTAZIONE DEI MOTORI
PIN_SENSO_ROTAZIONE_MOTORE_ASSE_Y = 24
PIN_SENSO_ROTAZIONE_MOTORE_ASSE_X = 23
PIN_SENSO_ROTAZIONE_MOTORE_ASSE_Z1 = 18
PIN_SENSO_ROTAZIONE_MOTORE_ASSE_Z2 = 26

# PIN DEL RASPBERRY DI ABILITAZIONE MOTORI
PIN_ABILITAZIONE_MOTORE_ASSE_Y = 19
PIN_ABILITAZIONE_MOTORE_ASSE_X = 13
PIN_ABILITAZIONE_MOTORE_ASSE_Z1 = 6
PIN_ABILITAZIONE_MOTORE_ASSE_Z2 = 5

# SETUP PIN
GPIO.setmode(GPIO.BCM)  #tipo di riferimento, numerazione della cpu
GPIO.setwarnings(False)
GPIO.setup(PIN_STEP_MOTORE_ASSE_Y, GPIO.OUT)  #imposto pin come uscita
GPIO.setup(PIN_STEP_MOTORE_ASSE_X, GPIO.OUT)  #imposto pin come uscita
GPIO.setup(PIN_STEP_MOTORE_ASSE_Z1, GPIO.OUT)  #imposto pin come uscita
GPIO.setup(PIN_STEP_MOTORE_ASSE_Z2, GPIO.OUT)  #imposto pin come uscita
GPIO.setup(PIN_SENSO_ROTAZIONE_MOTORE_ASSE_Y, GPIO.OUT)  #imposto pin come uscita
GPIO.setup(PIN_SENSO_ROTAZIONE_MOTORE_ASSE_X, GPIO.OUT)  #imposto pin come uscita
GPIO.setup(PIN_SENSO_ROTAZIONE_MOTORE_ASSE_Z1, GPIO.OUT)  #imposto pin come uscita
GPIO.setup(PIN_SENSO_ROTAZIONE_MOTORE_ASSE_Z2, GPIO.OUT)  #imposto pin come uscita
GPIO.setup(PIN_ABILITAZIONE_MOTORE_ASSE_Y, GPIO.OUT)  #imposto pin come uscita
GPIO.setup(PIN_ABILITAZIONE_MOTORE_ASSE_X, GPIO.OUT)  #imposto pin come uscita
GPIO.setup(PIN_ABILITAZIONE_MOTORE_ASSE_Z1, GPIO.OUT)  #imposto pin come uscita
GPIO.setup(PIN_ABILITAZIONE_MOTORE_ASSE_Z2, GPIO.OUT)  #imposto pin come uscita


GPIO.output(PIN_STEP_MOTORE_ASSE_Y, GPIO.HIGH)
GPIO.output(PIN_STEP_MOTORE_ASSE_X, GPIO.HIGH)
GPIO.output(PIN_STEP_MOTORE_ASSE_Z1, GPIO.HIGH)
GPIO.output(PIN_STEP_MOTORE_ASSE_Z2, GPIO.HIGH)

GPIO.output(PIN_STEP_MOTORE_ASSE_Y, GPIO.LOW)
GPIO.output(PIN_STEP_MOTORE_ASSE_X, GPIO.LOW)
GPIO.output(PIN_STEP_MOTORE_ASSE_Z1, GPIO.LOW)
GPIO.output(PIN_STEP_MOTORE_ASSE_Z2, GPIO.LOW)
GPIO.output(PIN_SENSO_ROTAZIONE_MOTORE_ASSE_Y, GPIO.LOW)
GPIO.output(PIN_SENSO_ROTAZIONE_MOTORE_ASSE_X, GPIO.LOW)
GPIO.output(PIN_SENSO_ROTAZIONE_MOTORE_ASSE_Z1, GPIO.LOW)
GPIO.output(PIN_SENSO_ROTAZIONE_MOTORE_ASSE_Z2, GPIO.LOW)
